# -*- coding: utf-8 -*-
"""10.SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvBs1yMBXpRkKTEuSp98_yGl-YxVoc1k
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Train SVM model
model = SVC(kernel='linear')  # You can also try 'rbf', 'poly'
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))