# -*- coding: utf-8 -*-
"""11.AppEMTechniques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUuIS5bxmVt3k7vgH7h4LGYSPneNjt2N
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score

# Load data
data = load_iris()
X, y = data.data, data.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# 🌳 Bagging using Random Forest
bag_model = RandomForestClassifier(n_estimators=50)
bag_model.fit(X_train, y_train)
bag_pred = bag_model.predict(X_test)

# 🚀 Boosting using AdaBoost
boost_model = AdaBoostClassifier(n_estimators=50)
boost_model.fit(X_train, y_train)
boost_pred = boost_model.predict(X_test)

# 🎯 Print results
print("Bagging (Random Forest) Accuracy:", accuracy_score(y_test, bag_pred))
print("Boosting (AdaBoost) Accuracy:", accuracy_score(y_test, boost_pred))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.3, random_state=42)

# Random Forest Model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Prediction and Evaluation
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))