# -*- coding: utf-8 -*-
"""12.AppClusteriingAlgorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMTQJ6baQVDp0lJgaefbNMd4aLhME0-1
"""

from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris = load_iris()
# Use same iris data
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(iris.data)
labels = kmeans.labels_

# Visualizing clusters
plt.scatter(iris.data[:, 0], iris.data[:, 1], c=labels)
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.title('K-Means Clustering')
plt.show()