# -*- coding: utf-8 -*-
"""13.EMforBayesianNetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMwFgfXPw_wtV0uEnAwjUDplzql2Db9w
"""

from sklearn.datasets import load_iris
from sklearn.mixture import GaussianMixture

# Load the Iris dataset
iris = load_iris()

# Fit a Gaussian Mixture Model
gmm = GaussianMixture(n_components=3, random_state=42)
gmm.fit(iris.data)

# Predict cluster labels
gmm_labels = gmm.predict(iris.data)

# Display the results
print("Cluster Labels:", gmm_labels)