# -*- coding: utf-8 -*-
"""14.NeuralNetworks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJpWhbdWWgnvok0CKyu25Ols02JjIwQE
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

# Data preparation
iris = load_iris()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(iris.data)

# Neural Network
model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_scaled, iris.target, epochs=50, verbose=0)
loss, acc = model.evaluate(X_scaled, iris.target)
print("Neural Network Accuracy:", acc)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Load the Iris dataset
iris = load_iris()

# Scale the input features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(iris.data)

# Neural Network Model
model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')  # 3 output classes
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(X_scaled, iris.target, epochs=50, verbose=0)

# Evaluate the model
loss, acc = model.evaluate(X_scaled, iris.target)
print("✅ Neural Network Accuracy:", round(acc * 100, 2), "%")