# -*- coding: utf-8 -*-
"""16.Dijkstra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuJXWyA4nDko8k1uYUtNT5aE74gt9u6H
"""

import heapq

def dijkstra(graph, start, end):
    heap = [(0, start)]
    dist = {start: 0}
    parent = {}

    while heap:
        cost, node = heapq.heappop(heap)
        if node == end:
            path = []
            while node:
                path.append(node)
                node = parent.get(node)
            return path[::-1], cost

        for neighbor, wt in graph.get(node, []):
            new_cost = cost + wt
            if new_cost < dist.get(neighbor, float('inf')):
                dist[neighbor] = new_cost
                parent[neighbor] = node
                heapq.heappush(heap, (new_cost, neighbor))

    return [], float('inf')

# Example
graph = {
    'A': [('B', 1), ('C', 4)],
    'B': [('C', 2), ('D', 5)],
    'C': [('D', 1)],
    'D': []
}

path, cost = dijkstra(graph, 'A', 'D')
print(f"Shortest path: {path}, Cost: {cost}")