# -*- coding: utf-8 -*-
"""17.LimitMemory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHT2vwbcBBXZDYqNFMOt_DJLQOZnEybd
"""

def depth_limited_dfs(graph, start, goal, limit):
    def dfs(node, path, depth):
        if depth > limit:
            return None
        if node == goal:
            return path
        for neighbor in graph.get(node, []):
            if neighbor not in path:
                result = dfs(neighbor, path + [neighbor], depth + 1)
                if result:
                    return result
        return None

    return dfs(start, [start], 0)

graph = {
    'A': ['B', 'C'],
    'B': ['D'],
    'C': ['E', 'F'],
    'D': [],
    'E': [],
    'F': ['G'],
    'G': []
}

path = depth_limited_dfs(graph, 'A', 'G', 3)
print(f"Path within depth limit: {path}")