# -*- coding: utf-8 -*-
"""18.QuizApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-JUNSVeHcujNPH2Q1-4dKc25FWrL_kR
"""

def show_intro():
    print("\n📚 Welcome to the Conditional Probability Quiz App!")
    print("👉 You'll learn and test your knowledge on how to calculate the probability of an event given another event.\n")

def ask_question():
    print("🎯 Question:")
    print("Given:")
    print("- P(A ∩ B) = 0.12 (probability of both A and B)")
    print("- P(B) = 0.3 (probability of B)\n")
    print("What is the conditional probability P(A|B)?")
    print("a) 0.04")
    print("b) 0.3")
    print("c) 0.12")
    print("d) 0.4\n")

    answer = input("Your answer (a/b/c/d): ").strip().lower()

    if answer == 'd':
        print("✅ Correct! P(A|B) = P(A ∩ B) / P(B) = 0.12 / 0.3 = 0.4")
    else:
        print("❌ Incorrect.")
        print("💡 Correct answer: d) 0.4")
        print("Formula: P(A|B) = P(A ∩ B) / P(B)")

def main():
    show_intro()
    ask_question()
    print("\n✨ Thank you for using the quiz app! Keep practicing!")

if __name__ == "__main__":
    main()

def bayes_theorem(prior_A, prob_B_given_A, prob_B):
    """P(A|B) = P(B|A) * P(A) / P(B)"""
    return (prob_B_given_A * prior_A) / prob_B

# Sample Quiz
print("Quiz: What is the probability of having a disease given a positive test?")
prior_disease = 0.01          # P(Disease)
prob_positive_given_disease = 0.9  # P(Pos | Disease)
prob_positive = 0.05          # P(Pos)

posterior = bayes_theorem(prior_disease, prob_positive_given_disease, prob_positive)
print(f"Probability of disease given positive test: {posterior:.2%}")

