# -*- coding: utf-8 -*-
"""20.PredictRegressionModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJwRXJQjUssUTNZ7KeWyWxIVJNPGIWO9
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Sample data: X (feature), y (target)
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2.5, 3.5, 5.0, 6.5, 8.0])

model = LinearRegression()
model.fit(X, y)

# Predict and plot
predicted = model.predict(X)
plt.scatter(X, y, color='blue')
plt.plot(X, predicted, color='red')
plt.xlabel('Input X')
plt.ylabel('Output y')
plt.title('Linear Regression')
plt.show()

print(f"Coefficient: {model.coef_[0]}, Intercept: {model.intercept_}")