# -*- coding: utf-8 -*-
"""3. A Star.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lyTxnXcVf8Fsvj4aR8Pg-BiDN_6-bk5
"""

def a_star(graph, start, goal, heuristic):
    open_list = [(start, [start], 0)]  # (current_node, path, cost_so_far)

    while open_list:
        open_list.sort(key=lambda x: x[2] + heuristic[x[0]])  # sort by f = g + h
        current, path, cost = open_list.pop(0)

        if current == goal:
            return path

        for neighbor, step_cost in graph.get(current, []):
            if neighbor not in path:
                total_cost = cost + step_cost
                open_list.append((neighbor, path + [neighbor], total_cost))

    return None
graph = {
    'A': [('B', 1), ('C', 3)],
    'B': [('D', 1), ('E', 4)],
    'C': [('F', 2)],
    'D': [],
    'E': [('F', 1)],
    'F': []
}

heuristic = {'A': 5, 'B': 4, 'C': 2, 'D': 6, 'E': 2, 'F': 0}

result = a_star(graph, 'A', 'F', heuristic)

print("Path found:" if result else "No path found.")
print(" -> ".join(result) if result else "")