# -*- coding: utf-8 -*-
"""4.MemoryBound.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIP5zg2vNGqPk7I4eaZcBEBTSbbTBZ5c
"""

def memory_bounded_a_star(graph, start, goal, heuristic, memory_limit):
    open_list = [(start, [start], 0)]  # (node, path, cost)

    while open_list:
        open_list.sort(key=lambda x: x[2] + heuristic[x[0]])
        open_list = open_list[:memory_limit]  # Limit memory usage
        current, path, cost = open_list.pop(0)

        if current == goal:
            return path

        for neighbor, step_cost in graph.get(current, []):
            if neighbor not in path:
                open_list.append((neighbor, path + [neighbor], cost + step_cost))

    return None
graph = {
    'A': [('B', 1), ('C', 3)],
    'B': [('D', 1), ('E', 4)],
    'C': [('F', 2)],
    'D': [],
    'E': [('F', 1)],
    'F': []
}

heuristic = {'A': 5, 'B': 4, 'C': 2, 'D': 6, 'E': 2, 'F': 0}

result = memory_bounded_a_star(graph, 'A', 'F', heuristic, memory_limit=3)

print("Path found:" if result else "No path found.")
print(" -> ".join(result) if result else "")